/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ICarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    ICarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    ICarbonLanguage: typeof import('~icons/carbon/language')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    ICarbonWarning: typeof import('~icons/carbon/warning')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
